name: Check - mdlint

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths:
      - "**.md"
      - "hack/check/check-mdlint.sh"

jobs:
  checkmdlint:
    name: Check mdlint
    # Only run this job if we're in the main repo, not a fork.
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code by commit
        uses: actions/checkout@v4

      - name: Ensure dependencies installed
        shell: bash
        run: |
          make ensure-deps

      - name: Run mdlint
        run: |
          make mdlint
