name: Check - static

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths:
      - "deepgram/**.py"

jobs:
  checkstatic:
    name: Check static
    # Only run this job if we're in the main repo, not a fork.
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code by commit
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ensure dependencies installed
        shell: bash
        run: |
          make ensure-deps

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r examples/requirements-examples.txt

      - name: Run mdlint
        run: |
          make static
